[package]
name = "contact_emailer"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.97"
csv = "1.3.1"
dotenv = "0.15.0"
eml-parser = "0.1.4"
inquire = "0.7.5"
lettre = "0.11.15"
owo-colors = "4.2.0"
